# Basic
title: 李俊
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: Azad_jun
# 头像里面的描述
avatarDesc: java / 云计算
url: "https://azadjun.github.io/"

# Comment
comment:    
    duoshuo: Azad_jun

# Social
social:
    weibo: 1816985934 
    github: azadjun
    # twitter: 
    mail: 575098618@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: e777d436031d5ed12bac89e17bee0361  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-93132551-1   
    host: auto  

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


